name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  gdscript-lint:
    name: GDScript Lint
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check GDScript formatting
        run: |
          find . -name "*.gd" -exec echo "Checking {}" \;
          # Basic syntax check - Godot will validate scripts during project check
          godot --headless --check-only --script-debug-to-stdout --verbose || true

  project-validation:
    name: Project Validation
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Validate project
        run: |
          godot --headless --editor --quit --path .
